// This file is auto-generated by Supabase CLI via:
//   npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/lib/supabase/types.ts
//
// Until you have a Supabase project, this placeholder keeps TypeScript happy.
// Replace with the generated output after running the migration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          role: "admin" | "member";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: "admin" | "member";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: "admin" | "member";
          updated_at?: string;
        };
      };
      groups: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
        };
      };
      group_members: {
        Row: {
          id: string;
          group_id: string;
          user_id: string;
          role: "owner" | "member";
          joined_at: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          user_id: string;
          role?: "owner" | "member";
          joined_at?: string;
        };
        Update: {
          role?: "owner" | "member";
        };
      };
      group_invites: {
        Row: {
          id: string;
          group_id: string;
          token: string;
          created_by: string | null;
          max_uses: number | null;
          use_count: number;
          expires_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          token?: string;
          created_by?: string | null;
          max_uses?: number | null;
          use_count?: number;
          expires_at?: string | null;
          created_at?: string;
        };
        Update: {
          max_uses?: number | null;
          use_count?: number;
          expires_at?: string | null;
        };
      };
      events: {
        Row: {
          id: string;
          owner_id: string;
          group_id: string | null;
          title: string;
          description: string | null;
          event_type: "set_date" | "linked" | "mutable";
          target_date: string;
          original_target_date: string;
          is_completed: boolean;
          is_public: boolean;
          member_permissions: "view_only" | "view_comment" | "can_adjust";
          color: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          group_id?: string | null;
          title: string;
          description?: string | null;
          event_type: "set_date" | "linked" | "mutable";
          target_date: string;
          original_target_date?: string;
          is_completed?: boolean;
          is_public?: boolean;
          member_permissions?: "view_only" | "view_comment" | "can_adjust";
          color?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          event_type?: "set_date" | "linked" | "mutable";
          target_date?: string;
          is_completed?: boolean;
          is_public?: boolean;
          member_permissions?: "view_only" | "view_comment" | "can_adjust";
          color?: string;
          updated_at?: string;
        };
      };
      event_chains: {
        Row: {
          id: string;
          chain_name: string | null;
          predecessor_id: string;
          successor_id: string;
          link_type: "relative" | "absolute";
          offset_days: number | null;
          absolute_start_date: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          chain_name?: string | null;
          predecessor_id: string;
          successor_id: string;
          link_type: "relative" | "absolute";
          offset_days?: number | null;
          absolute_start_date?: string | null;
          created_at?: string;
        };
        Update: {
          chain_name?: string | null;
          link_type?: "relative" | "absolute";
          offset_days?: number | null;
          absolute_start_date?: string | null;
        };
      };
      event_comments: {
        Row: {
          id: string;
          event_id: string;
          author_id: string;
          content: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          author_id: string;
          content: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          content?: string;
          updated_at?: string;
        };
      };
      date_adjustments: {
        Row: {
          id: string;
          event_id: string;
          user_id: string;
          reason_text: string;
          sentiment_score: number;
          days_suggested: number;
          days_chosen: number;
          date_before: string;
          date_after: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          user_id: string;
          reason_text: string;
          sentiment_score: number;
          days_suggested: number;
          days_chosen: number;
          date_before: string;
          date_after: string;
          created_at?: string;
        };
        Update: never;
      };
      nlp_feedback: {
        Row: {
          id: string;
          user_id: string;
          event_id: string | null;
          lr_slope: number;
          lr_intercept: number;
          lr_learning_rate: number;
          sample_count: number;
          last_updated: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          event_id?: string | null;
          lr_slope?: number;
          lr_intercept?: number;
          lr_learning_rate?: number;
          sample_count?: number;
          last_updated?: string;
        };
        Update: {
          lr_slope?: number;
          lr_intercept?: number;
          lr_learning_rate?: number;
          sample_count?: number;
          last_updated?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      is_group_member: {
        Args: { p_group_id: string };
        Returns: boolean;
      };
      activate_chain_successors: {
        Args: { p_event_id: string };
        Returns: void;
      };
    };
    Enums: Record<string, never>;
  };
};
