#!/usr/bin/env bash
# scripts/generate-secrets.sh
# ══════════════════════════════════════════════════════════════════════════════
# Generates all cryptographic secrets needed for a self-hosted TTLeave
# + Supabase deployment.
#
# Requirements: openssl, python3 (stdlib only — no extra packages needed)
#
# Usage:
#   bash scripts/generate-secrets.sh
#
# Paste the output block into your .env file.
# ══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

# ── Dependency checks ─────────────────────────────────────────────────────────
command -v openssl >/dev/null 2>&1 || { echo "ERROR: openssl not found. Install it first."; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "ERROR: python3 not found. Install it first."; exit 1; }

# ── Generate raw secrets ──────────────────────────────────────────────────────
# 64-char URL-safe random string for JWT_SECRET
JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n/+=' | cut -c1-64)

# 40-char password for Postgres
POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '\n/+=' | cut -c1-40)

# 28-char password for Kong dashboard
DASHBOARD_PASSWORD=$(openssl rand -base64 24 | tr -d '\n/+=' | cut -c1-28)

# 128-char hex string for Realtime SECRET_KEY_BASE
SECRET_KEY_BASE=$(openssl rand -hex 64)

# ── Generate ANON and SERVICE_ROLE JWTs ───────────────────────────────────────
# JWTs are HS256-signed with JWT_SECRET.
# Expiry: 10 years from now (standard for self-hosted API keys that don't rotate often).
# The python3 heredoc uses stdlib only (hmac, hashlib, base64, json, time).

generate_jwt() {
  local role="$1"
  local secret="$2"

  python3 << PYEOF
import hmac, hashlib, base64, json, time

secret = b"${secret}"
role   = "${role}"
now    = int(time.time())
exp    = now + (10 * 365 * 24 * 3600)  # 10 years

def b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()

header  = b64url(json.dumps({"alg": "HS256", "typ": "JWT"}).encode())
payload = b64url(json.dumps({"role": role, "iss": "supabase", "iat": now, "exp": exp}).encode())
msg     = f"{header}.{payload}".encode()
sig     = b64url(hmac.new(secret, msg, hashlib.sha256).digest())

print(f"{header}.{payload}.{sig}", end="")
PYEOF
}

ANON_KEY=$(generate_jwt "anon" "$JWT_SECRET")
SERVICE_ROLE_KEY=$(generate_jwt "service_role" "$JWT_SECRET")

# ── Print output ──────────────────────────────────────────────────────────────
cat << OUTPUT
# ============================================================
# Generated by scripts/generate-secrets.sh
# Generated: $(date -u "+%Y-%m-%d %H:%M:%S UTC")
#
# Paste this block into your .env file, then fill in
# the URL and SMTP sections below it.
# ============================================================

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
SECRET_KEY_BASE=${SECRET_KEY_BASE}

# ──────────────────────────────────────────────────────────────
# REMINDER: after pasting, also update these URL vars in .env:
#
#   SUPABASE_PUBLIC_URL=https://your-vps-ip-or-domain:8001
#   API_EXTERNAL_URL=https://your-vps-ip-or-domain:8001
#   SITE_URL=https://your-app-domain:3000
#   NEXT_PUBLIC_SUPABASE_URL=https://your-vps-ip-or-domain:8001
#   NEXT_PUBLIC_APP_URL=https://your-app-domain:3000
# ──────────────────────────────────────────────────────────────
OUTPUT
